### ISSUE TITLE
Pobieranie danych, błąd kompilera

### ISSUE THREAD

**Issue by KaspAdam** [wulkanowy/wulkanowy-web#44]
Przy uruchamianiu serwera pojawia się błąd: 
`ConnectionAbortedError: [WinError 10053] Nawiązane połączenie zostało przerwane przez oprogramowanie zainstalowane w komputerze-hoście`
oraz
`This program was made with an Unlicensed compiler.
 Please buy the PRO version to distribute your EXE.
 Press any key to continue . . .`
Po zalogowaniu wszystkie strony wyglądają tak: (Firefox)
![Zrzut ekranu 2021-02-02 222140](https://user-images.githubusercontent.com/66315787/106664218-0bfbe980-65a5-11eb-9ef7-25672d82db36.png)
![obraz](https://user-images.githubusercontent.com/66315787/106664343-3b125b00-65a5-11eb-917d-105f174621e8.png)
Po otworzeniu Chome w trybie:
`chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security`
otwierają się oceny, lecz nic innego.

**Comment by Pengwius** [comment]
Otwierać się mają tylko oceny - reszta powinna się pojawiać w konsoli. Co do ```ConnectionAbortedError: [WinError 10053] Nawiązane połączenie zostało przerwane przez oprogramowanie zainstalowane w komputerze-hoście``` - mnie taki błąd nie raczył odwiedzić (możliwe, że to za sprawą tego, iż pracuje na linuxie), lecz jak się dane pojawiaja w konsoli to wszytsko jest OK.

**Comment by KaspAdam** [comment]
> Otwierać się mają tylko oceny - reszta powinna się pojawiać w konsoli. Co do ```ConnectionAbortedError: [WinError 10053] Nawiązane połączenie zostało przerwane przez oprogramowanie zainstalowane w komputerze-hoście``` - mnie taki błąd nie raczył odwiedzić (możliwe, że to za sprawą tego, iż pracuje na linuxie), lecz jak się dane pojawiaja w konsoli to wszytsko jest OK.

Dzięki za odpowiedź, z niecierpliwością czekam na rozwój projektu. (Androidowy Wulkanowy działa świetnie).
